version: 2.1

# List of orbs
orbs:
  snyk: snyk/snyk@0.0.10

# List of jobs
jobs:
  pre_build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.13-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package-lock.json" }}
            - v2-dependencies-
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm ci
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v2-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      # Lint the source code
      - run:
          name: Linting
          command: npm run lint
      - snyk/scan
      # Cache local all project with dependencies
      - save_cache:
          key: v1-src-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .

  # The angular build job for web
  build_web_android:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.13-browsers
    steps:
      # Restore local dependencies from cache
      - restore_cache:
          key: v1-src-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      # Build project with different configuration based on the current branch
      - run:
          name: Building
          command: npm run build:prod
      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-web-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .

  # The angular build job for android
  cap_android:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.13-browsers
    steps:
      # Restore local dependencies from cache
      - restore_cache:
          key: v1-web-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      # Update dependencies & copy dist folder
      - run:
          name: Capacytor sync
          command: npx cap sync
      # Delete unused files
      - run:
          name: Delete icons in assets
          command: |
            shopt -s extglob;
            cd ./android/app/src/main/assets/public;
            rm -rv favicon.ico;
            rm -rv manifest.webmanifest;
            rm -rv ngsw-worker.js;
            rm -rv ngsw.json;
            rm -rv worker-basic.min.js;
            rm -rv safety-worker.js;
            rm -rv robots.txt;
            rm -rv assets/icons;
            sed '13,15d' -r index.html;
      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-android-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .

  deploy_web:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.13-browsers
    steps:
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore cache from the build job which contains the
      # dist folder that needs to be deployed
      - restore_cache:
          key: v1-web-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

  package_android:
    working_directory: ~/project/android
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      # Restore local dependencies from cache
      - restore_cache:
          key: v1-android-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Assemble debug apk
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo ${keystore} | base64 -d > app/keystore.jks
              ./gradlew :app:bundleRelease
            else
              ./gradlew :app:bundleDebug
            fi
      - store_artifacts:
          path: app/build/outputs/bundle/
          destination: bundles/
      - save_cache:
          paths:
            - ~/app/build/outputs/bundle/
          key: bundle-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      - pre_build
      - build_web_android:
          requires:
            - pre_build
      - cap_android:
          requires:
            - build_web_android
      - package_android:
          requires:
            - cap_android
      # The deploy job will only run on the filtered branches and
      # require the build job to be successful before it starts
      - deploy_web:
          requires:
            - build_web_android
          filters:
            branches:
              only: master
